# Generated by Django 4.2 on 2023-05-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handyman', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='thumbnail_url',
        ),
        migrations.AddField(
            model_name='job',
            name='display_order',
            field=models.IntegerField(null=True),
        ),
    ]
