# Generated by Django 4.2 on 2023-05-28 12:01

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handyman', '0004_jobdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetail',
            name='image_url',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jobdetail',
            name='type',
            field=models.CharField(default='X', max_length=20),
        ),
    ]
