# Generated by Django 4.2 on 2023-05-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handyman', '0006_alter_jobdetail_number_alter_jobdetail_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetail',
            name='image_width',
            field=models.IntegerField(null=True),
        ),
    ]
